server:
  error:
     include-stacktrace: never

spring:
  data-source:
    url: jdbc:mysql://localhost:3306/anime?&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa: 
    hibernate:
      ddl-auto: update


loggin:
  level:
    org:
      hibernate:
        SQL: DEBUG